olist_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'olist') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'olist') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'olist_dw') }}"
      schema: analytics
      threads: 2
