FROM apache/airflow:2.9.1-python3.11

ARG AIRFLOW_VERSION=2.9.1
ARG PYTHON_VERSION=3.11
ARG AIRFLOW_CONSTRAINTS_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"

COPY requirements/airflow.txt /tmp/requirements-airflow.txt
RUN pip install --no-cache-dir \
    --constraint "${AIRFLOW_CONSTRAINTS_URL}" \
    -r /tmp/requirements-airflow.txt

WORKDIR /opt/project
